version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run Tests
          command: echo hello
      - run:
          name: Connect to SSH and deploy
          command: ssh -o StrictHostKeyChecking=no -v $WEBUSER@$WEBIP -p $PORT "pwd && ./deployLandingPage.sh"
